[package]
name = "shapefile"
version = "0.2.0"
authors = ["tmontaigu <thomas.montaigu@laposte.net>"]
description = "Read & Write shapefiles in Rust"
license = "MIT"
readme = "README.md"
keywords = ["shapefile"]
homepage = "https://github.com/tmontaigu/shapefile-rs"
repository = "https://github.com/tmontaigu/shapefile-rs"
exclude = ["tests/data/*"]
#edition = "2018"

[dependencies]
byteorder = "1.2.7"
dbase = { git = "https://github.com/tmontaigu/dbase-rs" }
geo-types = {version = ">=0.4.0, <0.7.0", optional = true}


[package.metadata.docs.rs]
features = ["geo-types"]